removed debug command because of error messages
vagrant@vagrant:/vagrant/first_flask$ python3 project.py
* Serving Flask app "project" (lazy loading)
* Environment: production WARNING: Do not use the development server in a production environment.
Use a production WSGI server instead.
* Debug mode: on  * Running on
http://0.0.0.0:5000/ (Press CTRL+C to quit)
* Restarting with stat
Traceback (most recent call last):   File "project.py", line 11, in
<module>     app.run(host='0.0.0.0', port=5000)   File
"/usr/local/lib/python3.5/dist-packages/flask/app.py", line 943, in run
run_simple(host, port, self, **options)   File
"/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 988,
in run_simple     run_with_reloader(inner, extra_files,
reloader_interval, reloader_type)   File
"/usr/local/lib/python3.5/dist-packages/werkzeug/_reloader.py", line
332, in run_with_reloader     sys.exit(reloader.restart_with_reloader())
File "/usr/local/lib/python3.5/dist-packages/werkzeug/_reloader.py",
line 176, in restart_with_reloader     exit_code = subprocess.call(args,
env=new_environ, close_fds=False)   File
"/usr/lib/python3.5/subprocess.py", line 557, in call     with
Popen(*popenargs, **kwargs) as p:   File
"/usr/lib/python3.5/subprocess.py", line 947, in __init__
restore_signals, start_new_session)   File
"/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error